/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.conexao;
import static classes.conexao.statement;
import java.awt.Image;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;



/**
 *
 * @author Aluno
 */


public class pegarSenha extends javax.swing.JFrame {

    String tipo;
    int senha;
  
    
    public pegarSenha() {
        initComponents();
    }

    private void data(){
        Calendar now = Calendar.getInstance();
        Date dataHora = new Date();
   
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbData.setText(dt.format(dataHora));
        lbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbEsconde = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        senhaPreferencial = new javax.swing.JLabel();
        senhaNormal = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        sus = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedro SUS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Retire sua senha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lbEsconde.setBackground(new java.awt.Color(255, 255, 255));
        lbEsconde.setOpaque(true);
        jPanel1.add(lbEsconde, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 180, 180));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 180, 30));

        lbSenha.setBackground(new java.awt.Color(255, 255, 153));
        lbSenha.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSenha.setOpaque(true);
        jPanel1.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 180, 210));

        senhaPreferencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/preferencial.png"))); // NOI18N
        senhaPreferencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senhaPreferencialMouseClicked(evt);
            }
        });
        jPanel1.add(senhaPreferencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 220, 250));

        senhaNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/normal.png"))); // NOI18N
        senhaNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senhaNormalMouseClicked(evt);
            }
        });
        jPanel1.add(senhaNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 260));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 140, 40));

        lbData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 140, 40));

        sus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sus.png"))); // NOI18N
        jPanel1.add(sus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 50));

        lbTexto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTexto.setText("Retire sua senha!");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pegaSenha(String tipo){
        String sql = "Select max(tb01_num) from tb01_senha";
               sql += " where tb01_id_tipo = '" + tipo + "'";
            
        try{

        int seq;
        int maxSenha = 0;
        conexao objetoBD = new conexao();
        
        seq = 1;
                        
        objetoBD.conectar();

        ResultSet rs = statement.executeQuery(sql);  
       
        if (rs.next()) 
        {
             maxSenha = rs.getInt(1);
        }
        
        seq = maxSenha + 1; 
        senha = seq;
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    private void gravarSenha(){
        
        
        String sql = "INSERT INTO tb01_senha (tb01_id_tipo, tb01_num, tb01_data, tb01_hora, tb01_id_status)"
               +"VALUES ( '"+tipo+"','"+senha+"',NOW(), NOW(), 'N')";
        try{
        conexao objetoBD = new conexao();
        objetoBD.conectar();
        int qtdreg = objetoBD.runSQL(sql);
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    private void senhaNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senhaNormalMouseClicked

        tipo = "N";
        
        pegaSenha(tipo);
        gravarSenha();

        //lbSenha.setText(tipo + senha);
        lbSenha.setVisible(true);
        lbSenha.setText("<html><p style='font-size:18px; text-align:center; margin-left: 40px'>SENHA</p><br><p style='font-size:24px; margin-left: 48px'>"+tipo+""+senha+"</p><br><p style='font-size:10px;  margin-left: 45px'>"+lbData.getText()+"</p><p  style='font-size:10px; margin-left: 50px'>"+lbHora.getText()+"</p></html>");
        movimento();
    }//GEN-LAST:event_senhaNormalMouseClicked

    private void senhaPreferencialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senhaPreferencialMouseClicked

        tipo = "P";
        
        pegaSenha(tipo);
        gravarSenha();

        //lbSenha.setText(tipo + senha);
        lbSenha.setText("<html><p style='font-size:18px; text-align:center; margin-left: 40px'>SENHA</p><br><p style='font-size:24px; margin-left: 48px'>"+tipo+""+senha+"</p><br><p style='font-size:10px;  margin-left: 45px'>"+lbData.getText()+"</p><p  style='font-size:10px; margin-left: 50px'>"+lbHora.getText()+"</p></html>");
        lbSenha.setVisible(true);
        movimento();
    }//GEN-LAST:event_senhaPreferencialMouseClicked

    public void movimento()
    {
        new Thread()
        {
            public void run()
            { 

               int y = 550;
               int x = 0;
               
                while(true)
                {
                    if( x < 210 )
                    {
                        x = x+1; 
                        lbSenha.setLocation(y , x);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            
        }.start();
    }
    
    public void movimentoo()
    {
        new Thread()
        {
            public void run()
            { 
                while(true)
                {
                   int y = 800;
                   int x = 550;
                   lbTexto.setLocation(y , x);  

                    while(true)
                    {
                        if( y > -400 )
                        {
                            y = y - 1; 
                            lbTexto.setLocation(y , x);  
                        }
                        else
                        {
                            break;
                        }
                        try
                        {
                            sleep(5);
                        }
                        catch (Exception e)
                        {
                        }
                        
                    }
                    
                }
            }
            
        }.start();
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon imagem = new  ImageIcon(pegarSenha.class.getResource("/imagens/sus.png"));
        
        Image imag = imagem.getImage().getScaledInstance(sus.getWidth(), sus.getHeight(), Image.SCALE_DEFAULT);
        
        sus.setIcon(new ImageIcon(imag));
        
        lbSenha.setVisible(false);
        
        data();
        
        movimentoo();
    }//GEN-LAST:event_formWindowOpened

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEsconde;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel senhaNormal;
    private javax.swing.JLabel senhaPreferencial;
    private javax.swing.JLabel sus;
    // End of variables declaration//GEN-END:variables
}
