/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.conexao;
import static classes.conexao.statement;
import classes.estacoes;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import classes.qrCode;

/**
 *
 * @author Aluno
 */
public class bilheteMetro extends javax.swing.JFrame {
    
    int num = 0, maxNum = 0, terminal = 0;
    String estacao = "";

    Calendar now = Calendar.getInstance();
    Date dataHora = new Date();
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
    
    qrCode code = new qrCode();
    
    /**
     * Creates new form bilheteMetro
     */
    public bilheteMetro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnEmitir = new javax.swing.JButton();
        cbEstacao = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtTerminal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logoMetro = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        metroAnda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        linhas2 = new javax.swing.JLabel();
        linhas1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbEstacao = new javax.swing.JLabel();
        linhas3 = new javax.swing.JLabel();
        lbTerminal = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();
        linhas4 = new javax.swing.JLabel();
        linhas5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbEstacao1 = new javax.swing.JLabel();
        linhas6 = new javax.swing.JLabel();
        lbTerminal1 = new javax.swing.JLabel();
        lbNum1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        linhas7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        linhas8 = new javax.swing.JLabel();
        lbImpresso = new javax.swing.JLabel();
        lbCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metrô");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Geração de Bilhete Único");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btnEmitir.setBackground(new java.awt.Color(153, 153, 153));
        btnEmitir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEmitir.setForeground(new java.awt.Color(255, 255, 255));
        btnEmitir.setText("Emitir");
        btnEmitir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmitirMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 130, 40));

        cbEstacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbEstacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a estação" }));
        getContentPane().add(cbEstacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Estação:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        txtTerminal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Terminal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Bilhete:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        logoMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/metroLogo.png"))); // NOI18N
        getContentPane().add(logoMetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 150));

        lbNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 30));

        lbValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbValor.setText("R$3,90");
        getContentPane().add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 140, 40));

        lbData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 130, 40));

        metroAnda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/metroAnda.PNG"))); // NOI18N
        getContentPane().add(metroAnda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 120, 90));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 800, 90));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(204, 255, 255));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 250, 60));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 250, 20));

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linhas2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas2.setText("============================");
        painel.add(linhas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 20));

        linhas1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas1.setText("============================");
        painel.add(linhas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("COMPROVANTE DE VENDA");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BILHETE UNITÁRIO");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, -1));

        lbEstacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstacao.setText("ESTAÇÂO: xxxxxxxxxx");
        lbEstacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lbEstacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 20));

        linhas3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas3.setText("============================");
        painel.add(linhas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 20));

        lbTerminal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTerminal.setText("TERMINAL: x");
        lbTerminal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lbTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 20));

        lbNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNum.setText("NÚMERO: xx");
        lbNum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lbNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 20));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VALOR: R$3,90");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, -1));

        painel1.setBackground(new java.awt.Color(255, 255, 255));
        painel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linhas4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas4.setText("============================");
        painel1.add(linhas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 20));

        linhas5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas5.setText("============================");
        painel1.add(linhas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 20));

        jLabel12.setText("COMPROVANTE DE VENDA");
        painel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel13.setText("BILHETE UNITÁRIO");
        painel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lbEstacao1.setText("ESTAÇÂO: xxxxxxxxxx");
        painel1.add(lbEstacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 20));

        linhas6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas6.setText("============================");
        painel1.add(linhas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 20));

        lbTerminal1.setText("TERMINAL: x");
        painel1.add(lbTerminal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, 20));

        lbNum1.setText("NÚMERO: xx");
        painel1.add(lbNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 20));

        jLabel14.setText("VALOR: R$3,90");
        painel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        painel.add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 250, 340));

        linhas7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas7.setText("============================");
        painel.add(linhas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ATENÇÂO: Válido apenas para 1 viagem.");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, -1));
        painel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Usar preferencialmente em até 72 horas.");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, -1));

        linhas8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linhas8.setText("============================");
        painel.add(linhas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 20));

        lbImpresso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImpresso.setText("IMPRESSO EM: ##/##/####");
        lbImpresso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lbImpresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, -1));
        painel.add(lbCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 90));

        jPanel1.add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 250, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void pegaNumero(){
        String sql = "Select max(tb01_numero) from tb01_bilhete";
            
        try{

        conexao objetoBD = new conexao();
                        
        objetoBD.conectar();

        ResultSet rs = statement.executeQuery(sql);  
       
        if (rs.next()) 
        {
             maxNum = rs.getInt(1);
        }
        
        num = maxNum + 1; 
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    int id = 0, i = 0;
    String nom = null;
    
    private void carregaEstacao()
    {
           try 
        {              
              cbEstacao.removeAllItems();

              String sql = "SELECT * FROM tb02_estacao";
              
              conexao objetoBD = new conexao();
              objetoBD.conectar();
       
              ResultSet rs = statement.executeQuery(sql);
        
              //int id = 0;
              //String nom = null;
        
              cbEstacao.addItem(new estacoes(id, nom)); 
        
              while (rs.next())
              {
                id = rs.getInt("tb02_id_estacao");  
                nom = rs.getString("tb02_nome");  
                
                cbEstacao.addItem(new estacoes(id, nom));
              }
              
              objetoBD.desconectar();
              statement.close(); 
        }
               
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
       
    }
    
    private void estacaoId(){
        try 
        {              
            String sql = "SELECT * FROM tb02_estacao";
              
            conexao objetoBD = new conexao();
            objetoBD.conectar();
       
            ResultSet rs = statement.executeQuery(sql);   
            
            while (rs.next())
            {
               estacao = String.valueOf(cbEstacao.getSelectedItem());
               i = i + 1;
               
               nom = rs.getString("tb02_nome");
               
               if(estacao.equals(nom)){
                   break;
               }
            }
              
            objetoBD.desconectar();
            statement.close(); 
        }
               
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }
    
    private void gravaBilhete(){
        estacaoId();
        String sql = "INSERT INTO tb01_bilhete (tb01_numero, tb01_id_estacao, tb01_data, tb01_hora, tb01_terminal, tb01_valor)"
               +"VALUES ( '"+num+"','"+i+"', NOW(), '"+lbHora.getText()+"', '"+txtTerminal.getText()+"', 3.90)";
        try{
        conexao objetoBD = new conexao();
        objetoBD.conectar();
        int qtdreg = objetoBD.runSQL(sql);
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
        lbNumero.setText(""+num+"");
    }
    
    public void movimento()
    {
        new Thread()
        {
            public void run()
            { 

               int x = 530;
               int y = -250;
               
                while(true)
                {
                    if( y < 80 )
                    {
                        y = y+1; 
                        painel.setLocation(x , y);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            
        }.start();
    }
    
    public void movimento2()
    {
        new Thread()
        {
            public void run()
            { 
                while(true)
                {
                   int x = 800;
                   int y = 480;
                   metroAnda.setLocation(x , y);  

                    while(true)
                    {
                        if( x > -400 )
                        {
                            x = x - 1; 
                            metroAnda.setLocation(x , y);  
                        }
                        else
                        {
                            break;
                        }
                        try
                        {
                            sleep(5);
                        }
                        catch (Exception e)
                        {
                        }
                        
                    }
                    
                }
            }
            
        }.start();
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaEstacao();
        movimento2();
        
        class dataHora implements ActionListener{
            
            public void actionPerformed(ActionEvent ae){
                Calendar now = Calendar .getInstance();
                lbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
            }
        }
        
        Timer timer = new Timer(1000, new dataHora());
        timer.start();
        lbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        lbData.setText(dt.format(dataHora));
        
        
        ImageIcon imagem = new  ImageIcon(bilheteMetro.class.getResource("/imagens/metroLogo.png"));
        
        Image imag = imagem.getImage().getScaledInstance(logoMetro.getWidth(), logoMetro.getHeight(), Image.SCALE_DEFAULT);
        
        logoMetro.setIcon(new ImageIcon(imag));
        
        
        ImageIcon imagem2 = new  ImageIcon(bilheteMetro.class.getResource("/imagens/metroAnda.PNG"));
        
        Image imag2 = imagem2.getImage().getScaledInstance(metroAnda.getWidth(), metroAnda.getHeight(), Image.SCALE_DEFAULT);
        
        metroAnda.setIcon(new ImageIcon(imag2));
        
        painel.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

   
    private void codigoQr(){ 
        ImageIcon imageIcon = new ImageIcon(new ImageIcon( "E:\\Escola\\2 DS\\Desenvolvimento de Sistemas (tpa 2)\\metro\\src\\imagens\\bilhete.png").getImage().getScaledInstance(lbCode.getWidth(), lbCode.getHeight(), Image.SCALE_DEFAULT));

        lbCode.setIcon(imageIcon);
    }
    
    
    private void btnEmitirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmitirMouseClicked
        pegaNumero();
        gravaBilhete();
        
        
        painel.setVisible(true);
        lbEstacao.setText("ESTAÇÃO: " + estacao);
        lbNum.setText("NÚMERO: " + num);
        lbTerminal.setText("TERMINAL: " + txtTerminal.getText());
        lbImpresso.setText("IMPRESSO EM: " + lbData.getText() + " " + lbHora.getText());
        code.qrCode(lbNumero.getText());
        codigoQr();

        movimento();       
    }//GEN-LAST:event_btnEmitirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilheteMetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilheteMetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilheteMetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilheteMetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilheteMetro().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmitir;
    private javax.swing.JComboBox cbEstacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEstacao;
    private javax.swing.JLabel lbEstacao1;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbImpresso;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbNum1;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbTerminal;
    private javax.swing.JLabel lbTerminal1;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel linhas1;
    private javax.swing.JLabel linhas2;
    private javax.swing.JLabel linhas3;
    private javax.swing.JLabel linhas4;
    private javax.swing.JLabel linhas5;
    private javax.swing.JLabel linhas6;
    private javax.swing.JLabel linhas7;
    private javax.swing.JLabel linhas8;
    private javax.swing.JLabel logoMetro;
    private javax.swing.JLabel metroAnda;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painel1;
    private javax.swing.JTextField txtTerminal;
    // End of variables declaration//GEN-END:variables
}
