/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.conexao;
import classes.funcionario;
import static classes.conexao.statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class login extends javax.swing.JFrame {
    
    String caixa, nomeLogin, nomeESenha;
    int cod;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbxCaixa = new javax.swing.JComboBox<>();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Login do Mercado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 321, 53));

        cbxCaixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o caixa:", "1", "2", "3", "4", "5" }));
        cbxCaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(cbxCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 321, 50));

        btnEntrar.setBackground(new java.awt.Color(255, 153, 0));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 144, 51));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 321, 53));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) 
        {
            txtSenha.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyReleased

    private void consulta () {
        try {

              String sql = "SELECT * FROM tb04_funcionario WHERE tb04_nome = '"+txtNome.getText()+"' AND tb04_senha = '"+txtSenha.getText()+"'";
              
              conexao objetoBD = new conexao();
              objetoBD.conectar();
       
              ResultSet rs = statement.executeQuery(sql);

              if (rs.next())
              {
                cod = rs.getInt("tb04_cod_funcionario");  
                nomeLogin = rs.getString("tb04_nome");  
                
                funcionario obj = new funcionario();
                
                obj.guardaNome(nomeLogin);
                
                nomeESenha = "Colocou";
                
              }
              else {
                  JOptionPane.showMessageDialog(null , "Nome ou senha inválidos!", "Nome ou senha!", JOptionPane.ERROR_MESSAGE);
                  nomeESenha = "Não colocou";
              }
              
              objetoBD.desconectar();
              statement.close(); 
        }
        
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }
    
    private void caixa () {
        caixa = cbxCaixa.getSelectedItem().toString();
        if (caixa.equals("Selecione o caixa:")) {
            JOptionPane.showMessageDialog(null , "Selecione o caixa!", "Esqueceu do caixa?", JOptionPane.ERROR_MESSAGE);
        }
        else {
            funcionario obj = new funcionario();
            obj.guardaCaixa(caixa);
            
            if (nomeESenha == "Colocou") {
                telaCaixa tela = new telaCaixa();
                tela.setVisible(true);
                this.dispose();
            }
        }
    }
    
    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        consulta();
        caixa();
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> cbxCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
