/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import classes.conexao;
import static classes.conexao.statement;
import java.awt.Image;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class chamaSenha extends javax.swing.JFrame {

    String tipo;
    int minSenha = 0;
    int sorteio;
    
    DefaultListModel m = new DefaultListModel();
    
    private void data(){
        Calendar now = Calendar.getInstance();
        Date dataHora = new Date();
   
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbData.setText(dt.format(dataHora));
        lbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }
  
    
    public chamaSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbSenha = new javax.swing.JLabel();
        lbGuiche = new javax.swing.JLabel();
        lbSemSenhas = new javax.swing.JLabel();
        tv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mouse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        registros = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        sus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chama Senha");
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSenha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 80, 70));

        lbGuiche.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbGuiche.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(lbGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 130, 40));

        lbSemSenhas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSemSenhas.setForeground(new java.awt.Color(0, 102, 255));
        jPanel4.add(lbSemSenhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 210, 40));

        tv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/televisao.jpg"))); // NOI18N
        jPanel4.add(tv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 460, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Últimas Chamadas");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        mouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mouse.PNG"))); // NOI18N
        mouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseMouseClicked(evt);
            }
        });
        jPanel4.add(mouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, 150));

        registros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registros.setToolTipText("");
        jScrollPane2.setViewportView(registros);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 330));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        sus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sus.png"))); // NOI18N
        jPanel4.add(sus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Chamar a Senha");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pegaSenha(String tipo){
        String sql = "Select min(tb01_num) from tb01_senha";
               sql += " where tb01_id_tipo = '" + tipo + "' and tb01_id_status = 'N'";
            
        try{


        conexao objetoBD = new conexao();
        
                        
        objetoBD.conectar();

        ResultSet rs = statement.executeQuery(sql);  
       
        if (rs.next()) 
        {
             minSenha = rs.getInt(1);
        }
       
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    private void gravaBanco()
    {
     
        //dbHora = String.format("%1$tH:%1$tM:%1$tS", now);
        //SimpleDateFormat dt = new SimpleDateFormat("yyyy/MM/dd");
        //dbData = dt.format(dataHora);
        
        String sql = "Update tb01_senha set ";
               sql += " tb01_id_status = 'A'";
               sql += " where tb01_id_tipo = '" + tipo + "'";
               sql += " and   tb01_num = '" + minSenha + "'";
        
        try{

        conexao objetoBD = new conexao();
        objetoBD.conectar();
        
       int qtdreg = conexao.runSQL(sql);

        objetoBD.desconectar();
        
        }
        catch (Exception e){
             System.out.println(e.getMessage());
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        data();
        
        
        ImageIcon imagem = new  ImageIcon(chamaSenha.class.getResource("/imagens/televisao.jpg"));
        
        Image imag = imagem.getImage().getScaledInstance(tv.getWidth(), tv.getHeight(), Image.SCALE_DEFAULT);
        
        tv.setIcon(new ImageIcon(imag));
        
        
        ImageIcon imagem2 = new  ImageIcon(chamaSenha.class.getResource("/imagens/mouse.PNG"));
        
        Image imag2 = imagem2.getImage().getScaledInstance(mouse.getWidth(), mouse.getHeight(), Image.SCALE_DEFAULT);
        
        mouse.setIcon(new ImageIcon(imag2));

        
        ImageIcon imagem3 = new  ImageIcon(chamaSenha.class.getResource("/imagens/sus.png"));
        
        Image imag3 = imagem3.getImage().getScaledInstance(sus.getWidth(), sus.getHeight(), Image.SCALE_DEFAULT);
        
        sus.setIcon(new ImageIcon(imag3));
    }//GEN-LAST:event_formWindowOpened

    private void mostrar(){
        lbSenha.setText(tipo + minSenha);
        
        m.addElement("         " + lbSenha.getText());
        registros.setModel(m);
        
        Random sorte = new Random();
        sorteio = sorte.nextInt(9);
        sorteio = sorteio + 1;
        
        lbGuiche.setText("Guichê " + sorteio);
    }
    
   
    private void mouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMouseClicked
        
        tipo = "P";
        pegaSenha(tipo);
        lbSemSenhas.setText("");
        if(minSenha == 0){
            tipo = "N";
            pegaSenha(tipo);
            lbSemSenhas.setText("");
            if(minSenha == 0){
                lbSenha.setText("");
                lbSemSenhas.setText("Nenhuma senha!");
                lbGuiche.setText("");
               return;
            }
        }
        mostrar();
        gravaBanco();
        
    }//GEN-LAST:event_mouseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chamaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chamaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chamaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chamaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chamaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbGuiche;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbSemSenhas;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel mouse;
    private javax.swing.JList<String> registros;
    private javax.swing.JLabel sus;
    private javax.swing.JLabel tv;
    // End of variables declaration//GEN-END:variables
}
